### ISSUE TITLE
Accept patches only from rimraf

### ISSUE THREAD

**Issue by ceresith** [binki/rimraf-noglob#1]
Hello there,

We are about to switch from rimraf 2.2.8 to rimraf-noglob in our project, because of the breaking change that had been introduced with rimraf 2.3.

I would like to ask you to change the dependency of "rimraf": "^2.5.4" to "rimraf": "~2.5.4". The glob change had been a major change, but was introduced in a minor version. For us, this means we cannot trust the versioning of the rimraf module. Using rimraf-noglob instead is the simple solution, otherwise we would wrap the rimraf call ourself.

Cheers

**Comment by binki** [comment]
OK, I will update the dependency and publish to npm (hopefully as rimraf-noglob-2.5.4) shortly. I understand the concern, especially if some additional “feature” which turns out to be dangerous (like default-on globbing) comes in a new minor version or a new minor version’s method of disabling glob becomes incompatible with the mechanism rimraf-noglob uses.

Unfortunately, this will result in this package lagging behind upstream more quickly if there is ever active development. It looks like I should also publish an additional new version so that consumers of this library can benefit from any fixes or new features in rimraf-2.6. I will have to look into these details later, but if you are willing to continue opening issues as you find them or as new releases of rimraf come out that would be very helpful.

**Comment by binki** [comment]
Hmm, sorry for prematurely closing this issue. I probably should be using a PR against my own repository and only push to master once I tag it to get the auto-close stuff to work in a sensible way. Maybe next time ;-).

**Comment by binki** [comment]
OK, rimraf-noglob-2.5.4 has the minor version pinning and I will enforce that any higher versions use this pinning policy until further notice.

**Comment by ceresith** [comment]
Thank you very much! You are very fast :-)

**Comment by binki** [comment]
That is abnormal for me. You just caught me at a very good time ;-).
